### PR TITLE
Allow multicourt in search query

### PR DESCRIPTION
**Pull request by dragon-dxw**
Relies on https://github.com/nationalarchives/ds-caselaw-custom-api-client/pull/87

### CODE REVIEW

**Comment by dragon-dxw** [comment]
(I meant to mark this as draft, since there's changes I might wind up making)

**Comment by dragon-dxw** [comment]
Please don't merge on approval -- staging will break if the custom-api isn't deployed in tandem.

**Review by lozette — APPROVED** [review]
This looks great!

**Comment by dragon-dxw** [comment]
[👩‍⚖️Browse by multiple courts](https://trello.com/c/9SZ10awS/998-%F0%9F%91%A9%E2%9A%96%EF%B8%8Fbrowse-by-multiple-courts)

**Pull request merged**
